create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  age integer not null,
  gender text not null,
  quiz_type text not null,
  headline text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

alter table public.submissions enable row level security;

drop policy if exists "Allow insert for anon" on public.submissions;
create policy "Allow insert for anon"
  on public.submissions
  for insert
  to anon
  with check (true);

drop policy if exists "Allow select for anon" on public.submissions;
create policy "Allow select for anon"
  on public.submissions
  for select
  to anon
  using (true);
